COMPILER=gcc

# recompile only structs
structs:
	@$(COMPILER) -c src/structs.c -o bin/structs.o
	@$(COMPILER) bin/structs.o -o out/structs.out 

# Default
all:

# Clean up *.o and executable files
clean:
